apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  annotations:
    manifestival: new
  name: execute-yaml-task
  namespace: default
  uid: 2f769c6b-80d7-11ea-b4fd-000c29d7a6c9`
spec:
  inputs:
    params:
    - default: "/workspace/git-source"
      name: pathToContext
      type: string
    resources: {}
  steps:
  - name: clone-repo
    image: alpine/git
    env:
      - name: REPOSITORY
        value: "https://github.com/rodolphe-fontaine/policies"
      - name: REVISION
        value: master
    command: ["/bin/sh", "-c"]
    args:
      - set -e -o pipefail;
        git clone -q -b $REVISION $REPOSITORY .;
  - args:
    - -xv
    - -c
    - "cloudctl login -a https://icp-console.mcm113-8a2d3071712c7c965e5501bbbe7f8585-0001.par01.containers.appdomain.cloud --skip-ssl-validation -u admin -p 9xMmyVfibDbncDyMExzCKWEExRdCbZjP -n default"
    - "sleep 99999999; find ./policies/  -name \\*.yaml | xargs kubectl apply -f\n"
    command:
    - /bin/sh
    env:
    - name: pathToContext
      value: $(inputs.params.pathToContext)
    image: rfontain/kabanero-utils:demo
    name: execute
    resources: {}
    securityContext:
      privileged: false
    volumeMounts:
    - mountPath: /var/lib/containers
      name: varlibcontainers
  volumes:
  - emptyDir: {}
    name: varlibcontainers
