apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  annotations:
    manifestival: new
  name: execute-yaml-task
  namespace: kabanero
  ownerReferences:
  - apiVersion: kabanero.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Collection
    name: execute-yaml-task
    uid: e8e34bb6-f67c-4fd5-a27c-82273761ce81
  uid: 2f769c6b-80d7-11ea-b4fd-000c29d7a6c9`
spec:
  inputs:
    params:
    - default: /workspace/git-source
      name: pathToContext
      type: string
    resources:
    - name: git-source
      type: git
  steps:
  - args:
    - -xv
    - -c
    - "find $pathToContext -name \\*.yaml |xargs kubectl apply -f\n"
    command:
    - /bin/sh
    env:
    - name: pathToContext
      value: $(inputs.params.pathToContext)
    image: kabanero/kabanero-utils:0.3.0
    name: execute
    resources: {}
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/lib/containers
      name: varlibcontainers
  volumes:
  - emptyDir: {}
    name: varlibcontainers
