apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: create-policies-fromgit
spec:
  resources:
  - name: git-source
    type: git
  tasks:
  - name: create-policy
    params:
    - name: pathToContext
      value: /workspace/git-source
    resources:
      inputs:
      - name: git-source
        resource: git-source
    taskRef:
      name: execute-yaml-task
