apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  generation: 1
  name: policies-git
  namespace: kabanero
spec:
  params:
  - name: revision
    value: master
  - name: url
    value: https://github.com/rodolphe-fontaine/policies
  type: git
