apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline
spec:
  resources:
  - name: git-source
    type: git
  tasks:
  - name: create-policy
    params:
    - name: pathToContext
      value: /workspace/git-source
    resources:
      inputs: {}
    taskRef:
      name: execute-yaml-task
